app = "kakeibo-app"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  TZ = "Asia/Tokyo"

[http_service]
  internal_port = 8501
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false   # ← 自動停止オフ
  min_machines_running = 1     # ← 常時1台起動
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[[mounts]]
  source = "data"
  destination = "/data"
