
name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Ensure volume exists (data)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ vars.FLY_APP_NAME }}
          FLY_REGION: ${{ vars.FLY_REGION }}
        run: |
          set -e
          APP=${FLY_APP_NAME:-$(awk -F'"' '/^app\s*=/{print $2; exit}' fly.toml)}
          REGION=${FLY_REGION:-$(awk -F'"' '/^primary_region\s*=/{print $2; exit}' fly.toml)}
          echo "App=${APP} Region=${REGION}"
          set +e
          flyctl volumes list --app "$APP" | grep -q " data "
          HASVOL=$?
          set -e
          if [ "$HASVOL" -ne 0 ]; then
            flyctl volumes create data --size 1 --region "$REGION" --app "$APP"
          fi

      - name: Set runtime secrets (optional)
        if: ${{ secrets.AUTH_ENABLED != '' || secrets.AUTH_SALT != '' || secrets.AUTH_USERS_JSON != '' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ vars.FLY_APP_NAME }}
        run: |
          set -e
          APP=${FLY_APP_NAME:-$(awk -F'"' '/^app\s*=/{print $2; exit}' fly.toml)}
          if [ -n "${{ secrets.AUTH_ENABLED }}" ]; then
            flyctl secrets set AUTH_ENABLED=${{ secrets.AUTH_ENABLED }} --app "$APP"
          fi
          if [ -n "${{ secrets.AUTH_SALT }}" ]; then
            flyctl secrets set AUTH_SALT='${{ secrets.AUTH_SALT }}' --app "$APP"
          fi
          if [ -n "${{ secrets.AUTH_USERS_JSON }}" ]; then
            flyctl secrets set AUTH_USERS_JSON='${{ secrets.AUTH_USERS_JSON }}' --app "$APP"
          fi

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only

